export {
  DREAM_EXTENSION,
  DreamError,
  emptyDream,
  isDreamPath,
  isTrigger,
  parseDream,
  runOrder,
  serializeDream,
  triggerLabel,
  type ClaudeNode,
  type Dream,
  type DreamEdge,
  type DreamKind,
  type DreamNode,
  type FileTrigger,
  type GateNode,
  type HttpTrigger,
  type IntervalTrigger,
  type ManualTrigger,
  type NoteNode,
  type ShellNode,
  type TimeTrigger,
} from './core'
export { starterDreams, type StarterDream } from './starters'
